
require './game.coffee'
require './background.coffee'
require './boundingbox.coffee'
require './camera.coffee'
require './eventmanager.coffee'
require './game.coffee'
require './helpers.coffee'
require './keyboard.coffee'
require './map.coffee'
require './scene.coffee'
require './scenemanager.coffee'
require './sprite.coffee'
require './timer.coffee'
require './vector.coffee'
